### ISSUE TITLE
Create App to Check In attendees based on face

### ISSUE THREAD

**Issue by maniSbindra** [MumbaiHackerspace/Visage#13]
This app will be based on the Kiosk App at  https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk

**Comment by indcoder** [comment]
@maniSbindra We used this app in todays meetup?

**Comment by maniSbindra** [comment]
@indcoder app submitted as a part of PR 17 : https://github.com/MumbaiHackerspace/Visage/pull/17 is the app we used during the meetup on 18th June
