### ISSUE TITLE
Attendee Face Registration fails on edge.  

### ISSUE THREAD

**Issue by maniSbindra** [MumbaiHackerspace/Visage#22]
Attendee Face Registration fails on edge.  This seems to be a compatibility issue with the React Dropzone component which ins being used.

**Comment by indcoder** [comment]
Edge is not showing any console error. @maniSbindra Can you log this issue in the dropzone repo?

**Comment by maniSbindra** [comment]
It is due to URLSearchParams not currently being supported in edge.

**Comment by maniSbindra** [comment]
This is fixed after PR was merged
