### ISSUE TITLE
Docker Build failing

### ISSUE THREAD

**Issue by maniSbindra** [MumbaiHackerspace/Visage#27]
Docker Build Failing. useradd command not found. May need to replace my adduser and addgroup.

**Error:** 
Step 2/17 : RUN useradd --user-group --create-home --shell /bin/false app && mkdir -p /opt/app
 ---> Running in b9774cf118f7
**/bin/sh: useradd: not found**
The command '/bin/sh -c useradd --user-group --create-home --shell /bin/false app && mkdir -p /o
pt/app' returned a non-zero code: 127

**Comment by indcoder** [comment]
We also need to change the exposed port to 8080 since the app is now running under non root privilege and does not have access to default port 80
